#!/bin/bash
set -e

#Check arguments
if [[ -n "$3" ]]; then
	echo "USAGE: $0 [--quiet|--verbose] [<commit>]"
	echo "     --quiet    - suppress non-error messages"
	echo "     --verbose  - print added/removed count even when no warnings are added"
	echo "    <commit>    - the commit that should be checked, see gitrevisions(7)"
	echo "                  defaults to the currently checked out commit"
	exit 1
fi

if [[ "$1" == "--quiet" ]]; then
	QUIET="true"
	shift 1
elif [[ "$1" == "--verbose" ]]; then
	VERBOSE="true"
	shift 1
fi

COMMIT=$1
if [[ -z "$COMMIT" ]]; then
	COMMIT=`git describe`
fi

#Save the current branch / commit
ORIG=`git branch | grep '*' | cut -d" " -f2-`
if [[ $ORIG == "(no branch)" ]]; then
	ORIG=`git describe`
fi

#TODO: Check the state of the tree and index
if [ -a .checkcommit.prev ]; then
	echo ".checkcommit.prev exists, won't overwrite"
	exit 1;
fi
if [ -a .checkcommit.cur ]; then
	echo ".checkcommit.cur exists, won't overwrite"
	exit 1;
fi

TARGET=`git describe "$COMMIT"`
PARENT=`git describe "$COMMIT"^`

#Checkout the parent of the target
git checkout "$PARENT" &> /dev/null
mkdir -p .checkcommit.prev
set +e
ant clean &> /dev/null
ant checkstyle unit &> .checkcommit.prev/build
grep "\[cs:checkstyle\] " .checkcommit.prev/build | tail -n +2 | sort > .checkcommit.prev/checkstyle
grep "\[junit\] Testcase: .*\(FAILED\|ERROR\)" .checkcommit.prev/build | sort > .checkcommit.prev/junit
set -e

#Checkout the target
git checkout "$TARGET" &> /dev/null
mkdir -p .checkcommit.cur
set +e
ant clean &> /dev/null
ant checkstyle unit &> .checkcommit.cur/build
grep "\[cs:checkstyle\] " .checkcommit.cur/build | tail -n +2 | sort > .checkcommit.cur/checkstyle
grep "\[junit\] Testcase: .*\(FAILED\|ERROR\)" .checkcommit.cur/build | sort > .checkcommit.cur/junit
set -e

#Count differences
ADDED=`diff -u .checkcommit.prev .checkcommit.cur | tail -n+3 | grep "^+" | wc -l`
REMOVED=`diff -u .checkcommit.prev .checkcommit.cur | tail -n+3 | grep "^-" | wc -l`

#Count the Checkstyle warnings
CHECKSTYLE_ADDED=`diff -u .checkcommit.prev/checkstyle .checkcommit.cur/checkstyle | tail -n+3 | grep "^+" | wc -l`
CHECKSTYLE_REMOVED=`diff -u .checkcommit.prev/checkstyle .checkcommit.cur/checkstyle | tail -n+3 | grep "^-" | wc -l`
if [[ ! $QUIET ]]; then
	if [[ $CHECKSTYLE_ADDED -gt 0 || $VERBOSE ]]; then
		#Print any new warnings and the count
		set +e
		#TODO: Remove the initial +
		diff -u .checkcommit.prev/checkstyle .checkcommit.cur/checkstyle | tail -n+3 | grep "^+"
		set -e
		echo "`git describe`: $CHECKSTYLE_ADDED warnings added, $CHECKSTYLE_REMOVED removed"
	fi
fi

#Count the jUnit test failures
JUNIT_ADDED=`diff -u .checkcommit.prev/junit .checkcommit.cur/junit | tail -n+3 | grep "^+" | wc -l`
JUNIT_REMOVED=`diff -u .checkcommit.prev/junit .checkcommit.cur/junit | tail -n+3 | grep "^-" | wc -l`
if [[ ! $QUIET ]]; then
	if [[ $JUNIT_ADDED -gt 0 || $VERBOSE ]]; then
		#Print any new failures and the count
		set +e
		#TODO: Remove the initial +
		diff -u .checkcommit.prev/junit .checkcommit.cur/junit | tail -n+3 | grep "^+"
		set -e
		echo "`git describe`: $JUNIT_ADDED new failures, $JUNIT_REMOVED failures fixed"
	fi
fi

#Cleanup
rm -r .checkcommit.prev/ .checkcommit.cur/

#Checkout original branch
git checkout "$ORIG" &> /dev/null

#Exit with failure if warnings were added
if [[ $CHECKSTYLE_ADDED == "0" && $JUNIT_ADDED == "0" ]]; then
	exit 0
else
	exit 1
fi
